- type: antag
  id: Chimera
  name: role-subtype-Chimera
  antagonist: true
  setPreference: false
  objective: roles-antag-Chimera-objective
  guides: [ Letoferol ]

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChimera
  name: Chimera Role
  components:
  - type: MindRole
    antagPrototype: Chimera
    roleType: TeamAntagonist
    subtype: role-subtype-Chimera
  - type: MindRoleChimera

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChimeraInitial
  name: Initial Chimera
  components:
  - type: MindRole
    antagPrototype: LetoferolSleeper
    roleType: TeamAntagonist
    subtype: letoinfected
  - type: MindRoleChimera
